### ISSUE TITLE
PropTypes throwing errors in production?

### ISSUE THREAD

**Issue by prettymuchbryce** [reactjs/prop-types#17] opened 2017-04-11 00:28 UTC
Currently in React `15.5.0`, PropTypes called manually can result in an Error being thrown in production. This is due to the `productionTypeChecker` now being used in `15.5.0`. We suspect that the boolean argument passed to `invariant` was either intended to be flipped, or `warning` was intended to be used instead [here](https://github.com/reactjs/prop-types/blob/master/factory.js#L119). Passing `false` to invariant will [always throw an error](https://github.com/facebook/fbjs/blob/9b1198d7a6eb71fcd9f1d4b373ec473f2c88c34e/packages/fbjs/src/__forks__/invariant.js#L35).

We're currently seeing this occur in production as a result of using `react-router` v1.0.3, which expects PropType validators to [return errors](https://github.com/ReactTraining/react-router/blob/v1.0.3/modules/RouteUtils.js#L17), and doesn't account for any errors being thrown.

**Comment by franjohn21** [comment] 2017-04-11 00:41
Codepen: http://codepen.io/franjohn21/pen/Wjeemd

**Comment by franjohn21** [comment] 2017-04-11 02:20
If I'm reading [the docs](https://facebook.github.io/react/warnings/dont-call-proptypes.html) correctly, this functionality should throw an error in a *future* major release. 

```
In a future major release of React, the code that implements PropType validation functions will be stripped in production. Once this happens, any code that calls these functions manually (that isn't stripped in production) will throw an error.
```

So throwing an error now is unintentional and breaks production builds particularly where 3rd party libraries manually called proptype functions.

**Comment by aweary** [comment] 2017-04-11 14:44
Maybe @acdlite or @gaearon can shed some light on why `prop-types` is throwing in production before the next major React release.

**Comment by gaearon** [comment] 2017-04-11 15:07
This was an intentional breaking change in`prop-types` itself (as it is a completely new package) but I didn’t fully realize we switched React 15.5 **to actually use** the `prop-types` (and thus trigger the error).

We need to put out a fix for this asap, thanks for reporting.

**Closed** 2017-04-11 18:53 UTC
Labels: bug

**Comment by gaearon** [comment] 2017-04-11 19:00
This is fixed in `prop-types@15.5.7` and we'll update React 15.x to enforce depending on it soon.
In the meantime you should be able to run `rm -rf node_modules` and `npm install` to fix this.

**Comment by gaearon** [comment] 2017-04-11 19:37
Fixed in `react@15.4.4`.

**Comment by gaearon** [comment] 2017-04-11 19:43
In case anyone is confused, the intended behavior is explained here:

https://github.com/reactjs/prop-types/blob/master/README.md#difference-from-reactproptypes-dont-call-validator-functions

I verified that `react@15.4.4` restores the old behavior for `React.PropTypes`, fixing the `react-router@1.x` problem.

**Comment by bvaughn** [comment] 2017-04-11 19:44
react@15.5.4 ^

**Comment by gaearon** [comment] 2017-04-11 19:45
Thanks 😄 I keep typing that for some reason
